import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./Header/Header";
import Footer from "./[locale]/Footer/Footer";
import FAQ from "./[locale]/FAQ/page";
import Modals from "./[locale]/Modals/page";
import Dashbord from "./Dashbord/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      {/* <Dashbord/> */}

      {/* <Header/> */}
        {children}
        {/* <Modals/> */}
        {/* <Footer/> */}
        </body>

    </html>
  );
}
